### ISSUE TITLE
reporte 

### ISSUE THREAD

**Issue by ArturoAngonJose** [SistemasTecTlaxiaco/diseno-de-control-para-cajas-de-texto-ArturoAngonJose#2]
[Reporte TexBox.pdf](https://github.com/SistemasTecTlaxiaco/diseno-de-control-para-cajas-de-texto-ArturoAngonJose/files/6339456/Reporte.TexBox.pdf)

**Comment by Eva155** [comment]
Faltó la descripción y el índice
Calificación: 18 puntos
Calificó: Eva Aguilar Avendaño

**Comment by josealfredo79** [comment]
Bien hecho y revisado.
